name: Build and Deploy

on:
  push:
    branches:
      - main
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Vercel
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "Set the VERCEL_TOKEN secret in your repository."
            exit 1
          fi
          vercel --token ${{ secrets.VERCEL_TOKEN }}
